stages:
  - build
  - test
  - deploy

default:
  image: maven:3.8.6-openjdk-18

cache:
  paths:
    - .cache/repository
    # - dependances/

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.cache/repository"

build:
  stage: build
  script:
    - mvn clean compile
  artifacts:
    paths:
      - target/
    expire_in: 1 hour

test:
  stage: test
  script:
    - mvn test
  # dependencies:
  #   - build-backend

package:
  stage: deploy
  script:
    - mvn package
  artifacts:
    paths:
      - target/starter-1.0.0-SNAPSHOT-fat.jar
